// Generated by Selenium IDE
package tests;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1CryptoAlertTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1CryptoAlert() {
    driver.get("http://ec2-3-22-233-35.us-east-2.compute.amazonaws.com:8080/TeamCryptoAlert/register.html");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.name("userName")).click();
    driver.findElement(By.name("userName")).sendKeys("Bunson Honeydew");
    driver.findElement(By.name("userPass")).click();
    driver.findElement(By.name("userPass")).sendKeys("1234");
    driver.findElement(By.name("userEmail")).click();
    driver.findElement(By.name("userEmail")).sendKeys("bunson@gmail.com");
    driver.findElement(By.id("crypto1")).click();
    driver.findElement(By.id("crypto2")).click();
    driver.findElement(By.id("crypto3")).click();
    driver.findElement(By.id("crypto4")).click();
    driver.findElement(By.cssSelector("input:nth-child(19)")).click();
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.name("userName")).click();
    driver.findElement(By.name("userName")).sendKeys("Bunson Honeydew");
    driver.findElement(By.name("userPass")).click();
    driver.findElement(By.name("userPass")).sendKeys("bunson");
    driver.findElement(By.cssSelector("input:nth-child(5)")).click();
    driver.findElement(By.name("userName")).click();
    driver.findElement(By.name("userName")).sendKeys("admin1");
    driver.findElement(By.name("userPass")).click();
    driver.findElement(By.name("userPass")).sendKeys("admin");
    driver.findElement(By.cssSelector("input:nth-child(5)")).click();
    driver.findElement(By.cssSelector("form:nth-child(5) > input")).click();
  }
}